name: CodeCov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}